package store

import "github.com/KAA87/api-report.git/internal/app/model"

// CalculationDiagnosticTestsRepository ...
type CalculationDiagnosticTestsRepository struct {
	store *Store
}

// FindByDiagnosticTestId ...
func (r *CalculationDiagnosticTestsRepository) FindByDiagnosticTestId(diagnosticTestId int) (*model.CalculationDiagnosticTests, error) {
	t := &model.CalculationDiagnosticTests{}

	if err := r.store.db.QueryRow(
		"SELECT * from calculation_diagnostic_tests WHERE diagnostic_tests_id = ?",
		diagnosticTestId,
	).Scan(
		&t.ID,
		&t.DiagnosticTestsID,
		&t.DeviceUsersID,
		&t.PatientID,
		&t.Device,
		&t.Value1,
		&t.Fall1,
		&t.Value2,
		&t.Fall2,
		&t.Value3,
		&t.Fall3,
		&t.Value4,
		&t.Fall4,
		&t.Value5,
		&t.Fall5,
		&t.Value6,
		&t.Fall6,
		&t.Value7,
		&t.Fall7,
		&t.Value8,
		&t.Fall8,
		&t.Value9,
		&t.Fall9,
		&t.Value10,
		&t.Fall10,
		&t.Value11,
		&t.Fall11,
		&t.Value12,
		&t.Fall12,
		&t.Value13,
		&t.Fall13,
		&t.Value14,
		&t.Fall14,
		&t.Value15,
		&t.Fall15,
		&t.Value16,
		&t.Fall16,
		&t.Value17,
		&t.Fall17,
		&t.Value18,
		&t.Fall18,
		&t.Value19,
		&t.Fall19,
		&t.Value20,
		&t.Fall20,
		&t.Value21,
		&t.Fall21,
		&t.Value22,
		&t.Fall22,
		&t.Value23,
		&t.Fall23,
		&t.Value24,
		&t.Fall24,
		&t.Value25,
		&t.Fall25,
		&t.Value26,
		&t.Fall26,
		&t.Value27,
		&t.Fall27,
		&t.Value28,
		&t.Fall28,
		&t.Value29,
		&t.Fall29,
		&t.Value30,
		&t.Fall30,
		&t.Value31,
		&t.Fall31,
		&t.Value32,
		&t.Fall32,
		&t.Value33,
		&t.Fall33,
		&t.Value34,
		&t.Fall34,
		&t.Value35,
		&t.Fall35,
		&t.Value36,
		&t.Fall36,
		&t.Value37,
		&t.Fall37,
		&t.Value38,
		&t.Fall38,
		&t.Value39,
		&t.Fall39,
		&t.Value40,
		&t.Fall40,
		&t.Value41,
		&t.Fall41,
		&t.Value42,
		&t.Fall42,
		&t.Value43,
		&t.Fall43,
		&t.Value44,
		&t.Fall44,
		&t.Value45,
		&t.Fall45,
		&t.Value46,
		&t.Fall46,
		&t.Value47,
		&t.Fall47,
		&t.Countitempw,
		&t.Countitemac,
		&t.Countitemwa,
		&t.Createdate,
	); err != nil {
		return nil, err
	}

	return t, nil
}
